### ISSUE TITLE
Create krawler extension for OSHWA

### ISSUE THREAD

**Issue by traedamatic** [OPEN-NEXT/LOSH-krawler#3]
The krawl should extend with fetch logic for the OSHWA API

https://certificationapi.oshwa.org/documentation

The code will fetch the /api/projects  route to get the OSHWA projects: 

[https://certification.oshwa.org/list.html](https://certification.oshwa.org/list.html)

**Comment by moedn** [comment]
Hey ho, please also get the following _additional_ fields when fetching data from OSHWA:

- [ ] country
- [ ] certificationDate

- and store all types (`primaryType` and `addictionalType`s) and licenses (hardware, software, documentation) in the projects RDF. I'd like to create stats on OSHWA's categories and also show which kind of licenses have been used. That is primarily to come as close as feasible to the old OSHdata reports as people told me that they would love to have at least the information of those old reports in the new LOSH reports

**Comment by traedamatic** [comment]
Hey example from the oshwa krawler:

@prefix : <https://certification.oshwa.org/US002028.html/1.0.0/> .
@prefix okh: <https://github.com/OPEN-NEXT/OKH-LOSH/raw/master/OKH-LOSH.ttl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:Adafruit24lc32I2cEepromBreakout32kbit4KbStemmaQt a okh:Module ;
    rdfs:label "Adafruit 24LC32 I2C EEPROM Breakout - 32Kbit / 4 KB - Stemma QT" ;
    okh:additionalType "['Electronics']" ;
    okh:certificationDate "2021-08-19T00:00:00-04:00" ;
    okh:country "United States of America" ;
    okh:cpcPatentClass "H" ;
    okh:dataSource "OSHWA" ;
    okh:documentationLanguage "en" ;
    okh:documentationLicense "CC BY-SA" ;
    okh:export "[]" ;
    okh:function "Some microcontrollers, especially ARM Cortex-based devicess, don't have any built-in flash! What then? That's where this petite Adafruit 24LC32 I2C EEPROM Breakout comes in to help! With 32 Kbit (4 KByte) of storage, it's just the right amount of simple I2C-controllable storage. This sensor uses a 4-pin Sparkfun Qwiic-compatible connector called STEMMA QT, which allows the sensor to communicate over I2C without soldering. Click the link labeled 'Project Website' to find out more." ;
    okh:hardwareLicense "Other" ;
    okh:licensor "Adafruit Industries, LLC" ;
    okh:primaryType "Electronics" ;
    okh:repo <https://certification.oshwa.org/US002028.html> ;
    okh:repoHost "OSHWA" ;
    okh:softwareLicense "MIT" ;
    okh:source "[]" ;
    okh:spdxLicense <https://spdx.org/licenses/CC-BY-SA-4.0> ;
    okh:version "1.0.0" ;
    okh:versionOf <https://certification.oshwa.org/US002028.html> .
